<?php

namespace Packages\System\Database\Seeds;

use Packages\System\Models\SystemCounty;
use Illuminate\Database\Seeder;

class SystemCountyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            [
                'countyCode' => "AHOS",
                'countyName' => "ALTO HOSPICIO",
                'regionCode' => "R1",
                'ineCountyCode' => '998',
                'queryMode' => '1',
                'coverageName' => "ALTO HOSPICIO",
            ],
            [
                'countyCode' => "IQUI",
                'countyName' => "IQUIQUE",
                'regionCode' => "R1",
                'ineCountyCode' => '210',
                'queryMode' => '1',
                'coverageName' => "IQUIQUE",
            ],
            [
                'countyCode' => "POZO",
                'countyName' => "POZO ALMONTE",
                'regionCode' => "R1",
                'ineCountyCode' => '215',
                'queryMode' => '1',
                'coverageName' => "POZO ALMONTE",
            ],
            [
                'countyCode' => "ANTO",
                'countyName' => "ANTOFAGASTA",
                'regionCode' => "R2",
                'ineCountyCode' => '230',
                'queryMode' => '1',
                'coverageName' => "ANTOFAGASTA",
            ],
            [
                'countyCode' => "CALA",
                'countyName' => "CALAMA",
                'regionCode' => "R2",
                'ineCountyCode' => '225',
                'queryMode' => '1',
                'coverageName' => "CALAMA",
            ],
            [
                'countyCode' => "MARI",
                'countyName' => "MARIA ELENA",
                'regionCode' => "R2",
                'ineCountyCode' => '221',
                'queryMode' => '1',
                'coverageName' => "MARIA ELENA",
            ],
            [
                'countyCode' => "MEJI",
                'countyName' => "MEJILLONES",
                'regionCode' => "R2",
                'ineCountyCode' => '231',
                'queryMode' => '1',
                'coverageName' => "MEJILLONES",
            ],
            [
                'countyCode' => "SPAT",
                'countyName' => "SAN PEDRO DE ATACAMA",
                'regionCode' => "R2",
                'ineCountyCode' => '227',
                'queryMode' => '1',
                'coverageName' => "SAN PEDRO DE ATACAMA",
            ],
            [
                'countyCode' => "SGOR",
                'countyName' => "SIERRA GORDA",
                'regionCode' => "R2",
                'ineCountyCode' => '232',
                'queryMode' => '1',
                'coverageName' => "SIERRA GORDA",
            ],
            [
                'countyCode' => "TALT",
                'countyName' => "TALTAL",
                'regionCode' => "R2",
                'ineCountyCode' => '233',
                'queryMode' => '1',
                'coverageName' => "TALTAL",
            ],
            [
                'countyCode' => "TOCO",
                'countyName' => "TOCOPILLA",
                'regionCode' => "R2",
                'ineCountyCode' => '220',
                'queryMode' => '1',
                'coverageName' => "TOCOPILLA",
            ],
            [
                'countyCode' => "CALD",
                'countyName' => "CALDERA",
                'regionCode' => "R3",
                'ineCountyCode' => '241',
                'queryMode' => '1',
                'coverageName' => "CALDERA",
            ],
            [
                'countyCode' => "CHAN",
                'countyName' => "CHANARAL",
                'regionCode' => "R3",
                'ineCountyCode' => '235',
                'queryMode' => '1',
                'coverageName' => "CHANARAL",
            ],
            [
                'countyCode' => "COPI",
                'countyName' => "COPIAPO",
                'regionCode' => "R3",
                'ineCountyCode' => '240',
                'queryMode' => '1',
                'coverageName' => "COPIAPO",
            ],
            [
                'countyCode' => "DIEG",
                'countyName' => "DIEGO DE ALMAGRO",
                'regionCode' => "R3",
                'ineCountyCode' => '236',
                'queryMode' => '1',
                'coverageName' => "DIEGO DE ALMAGRO",
            ],
            [
                'countyCode' => "FREI",
                'countyName' => "FREIRINA",
                'regionCode' => "R3",
                'ineCountyCode' => '246',
                'queryMode' => '1',
                'coverageName' => "FREIRINA",
            ],
            [
                'countyCode' => "HUAS",
                'countyName' => "HUASCO",
                'regionCode' => "R3",
                'ineCountyCode' => '247',
                'queryMode' => '1',
                'coverageName' => "HUASCO",
            ],
            [
                'countyCode' => "TAMA",
                'countyName' => "TIERRA AMARILLA",
                'regionCode' => "R3",
                'ineCountyCode' => '242',
                'queryMode' => '1',
                'coverageName' => "TIERRA AMARILLA",
            ],
            [
                'countyCode' => "VALL",
                'countyName' => "VALLENAR",
                'regionCode' => "R3",
                'ineCountyCode' => '245',
                'queryMode' => '1',
                'coverageName' => "VALLENAR",
            ],
            [
                'countyCode' => "ANDA",
                'countyName' => "ANDACOLLO",
                'regionCode' => "R4",
                'ineCountyCode' => '253',
                'queryMode' => '1',
                'coverageName' => "ANDACOLLO",
            ],
            [
                'countyCode' => "COMB",
                'countyName' => "COMBARBALA",
                'regionCode' => "R4",
                'ineCountyCode' => '263',
                'queryMode' => '1',
                'coverageName' => "COMBARBALA",
            ],
            [
                'countyCode' => "COQU",
                'countyName' => "COQUIMBO",
                'regionCode' => "R4",
                'ineCountyCode' => '252',
                'queryMode' => '1',
                'coverageName' => "COQUIMBO",
            ],
            [
                'countyCode' => "ILLA",
                'countyName' => "ILLAPEL",
                'regionCode' => "R4",
                'ineCountyCode' => '270',
                'queryMode' => '1',
                'coverageName' => "ILLAPEL",
            ],
            [
                'countyCode' => "LASE",
                'countyName' => "LA SERENA",
                'regionCode' => "R4",
                'ineCountyCode' => '250',
                'queryMode' => '1',
                'coverageName' => "LA SERENA",
            ],
            [
                'countyCode' => "LVIL",
                'countyName' => "LOS VILOS",
                'regionCode' => "R4",
                'ineCountyCode' => '272',
                'queryMode' => '1',
                'coverageName' => "LOS VILOS",
            ],
            [
                'countyCode' => "MOPA",
                'countyName' => "MONTE PATRIA",
                'regionCode' => "R4",
                'ineCountyCode' => '262',
                'queryMode' => '1',
                'coverageName' => "MONTE PATRIA",
            ],
            [
                'countyCode' => "OVAL",
                'countyName' => "OVALLE",
                'regionCode' => "R4",
                'ineCountyCode' => '260',
                'queryMode' => '1',
                'coverageName' => "OVALLE",
            ],
            [
                'countyCode' => "PUNI",
                'countyName' => "PUNITAQUI",
                'regionCode' => "R4",
                'ineCountyCode' => '264',
                'queryMode' => '1',
                'coverageName' => "PUNITAQUI",
            ],
            [
                'countyCode' => "SALA",
                'countyName' => "SALAMANCA",
                'regionCode' => "R4",
                'ineCountyCode' => '271',
                'queryMode' => '1',
                'coverageName' => "SALAMANCA",
            ],
            [
                'countyCode' => "VICU",
                'countyName' => "VICUNA",
                'regionCode' => "R4",
                'ineCountyCode' => '254',
                'queryMode' => '1',
                'coverageName' => "VICUNA",
            ],
            [
                'countyCode' => "ALGA",
                'countyName' => "ALGARROBO",
                'regionCode' => "R5",
                'ineCountyCode' => '324',
                'queryMode' => '1',
                'coverageName' => "ALGARROBO",
            ],
            [
                'countyCode' => "CART",
                'countyName' => "CARTAGENA",
                'regionCode' => "R5",
                'ineCountyCode' => '321',
                'queryMode' => '1',
                'coverageName' => "CARTAGENA",
            ],
            [
                'countyCode' => "CASA",
                'countyName' => "CASABLANCA",
                'regionCode' => "R5",
                'ineCountyCode' => '316',
                'queryMode' => '1',
                'coverageName' => "CASABLANCA",
            ],
            [
                'countyCode' => "CCON",
                'countyName' => "CONCON",
                'regionCode' => "R5",
                'ineCountyCode' => '318',
                'queryMode' => '1',
                'coverageName' => "CONCON",
            ],
            [
                'countyCode' => "QSCO",
                'countyName' => "EL QUISCO",
                'regionCode' => "R5",
                'ineCountyCode' => '323',
                'queryMode' => '1',
                'coverageName' => "EL QUISCO",
            ],
            [
                'countyCode' => "TABO",
                'countyName' => "EL TABO",
                'regionCode' => "R5",
                'ineCountyCode' => '322',
                'queryMode' => '1',
                'coverageName' => "EL TABO",
            ],
            [
                'countyCode' => "HIJU",
                'countyName' => "HIJUELAS",
                'regionCode' => "R5",
                'ineCountyCode' => '304',
                'queryMode' => '1',
                'coverageName' => "HIJUELAS",
            ],
            [
                'countyCode' => "LACA",
                'countyName' => "LA CALERA",
                'regionCode' => "R5",
                'ineCountyCode' => '302',
                'queryMode' => '1',
                'coverageName' => "LA CALERA",
            ],
            [
                'countyCode' => "LACR",
                'countyName' => "LA CRUZ",
                'regionCode' => "R5",
                'ineCountyCode' => '301',
                'queryMode' => '1',
                'coverageName' => "LA CRUZ",
            ],
            [
                'countyCode' => "LALI",
                'countyName' => "LA LIGUA",
                'regionCode' => "R5",
                'ineCountyCode' => '275',
                'queryMode' => '1',
                'coverageName' => "LA LIGUA",
            ],
            [
                'countyCode' => "LIMA",
                'countyName' => "LIMACHE",
                'regionCode' => "R5",
                'ineCountyCode' => '305',
                'queryMode' => '1',
                'coverageName' => "LIMACHE",
            ],
            [
                'countyCode' => "LLAY",
                'countyName' => "LLAY LLAY",
                'regionCode' => "R5",
                'ineCountyCode' => '294',
                'queryMode' => '1',
                'coverageName' => "LLAY LLAY",
            ],
            [
                'countyCode' => "LAND",
                'countyName' => "LOS ANDES",
                'regionCode' => "R5",
                'ineCountyCode' => '285',
                'queryMode' => '1',
                'coverageName' => "LOS ANDES",
            ],
            [
                'countyCode' => "NOGA",
                'countyName' => "NOGALES",
                'regionCode' => "R5",
                'ineCountyCode' => '303',
                'queryMode' => '1',
                'coverageName' => "NOGALES",
            ],
            [
                'countyCode' => "OLMU",
                'countyName' => "OLMUE",
                'regionCode' => "R5",
                'ineCountyCode' => '306',
                'queryMode' => '1',
                'coverageName' => "OLMUE",
            ],
            [
                'countyCode' => "PUCH",
                'countyName' => "PUCHUNCAVI",
                'regionCode' => "R5",
                'ineCountyCode' => '313',
                'queryMode' => '1',
                'coverageName' => "PUCHUNCAVI",
            ],
            [
                'countyCode' => "QLTA",
                'countyName' => "QUILLOTA",
                'regionCode' => "R5",
                'ineCountyCode' => '300',
                'queryMode' => '1',
                'coverageName' => "QUILLOTA",
            ],
            [
                'countyCode' => "QUIL",
                'countyName' => "QUILPUE",
                'regionCode' => "R5",
                'ineCountyCode' => '314',
                'queryMode' => '1',
                'coverageName' => "QUILPUE",
            ],
            [
                'countyCode' => "QUIN",
                'countyName' => "QUINTERO",
                'regionCode' => "R5",
                'ineCountyCode' => '312',
                'queryMode' => '1',
                'coverageName' => "QUINTERO",
            ],
            [
                'countyCode' => "SANT",
                'countyName' => "SAN ANTONIO",
                'regionCode' => "R5",
                'ineCountyCode' => '320',
                'queryMode' => '1',
                'coverageName' => "SAN ANTONIO",
            ],
            [
                'countyCode' => "SFEL",
                'countyName' => "SAN FELIPE",
                'regionCode' => "R5",
                'ineCountyCode' => '290',
                'queryMode' => '1',
                'coverageName' => "SAN FELIPE",
            ],
            [
                'countyCode' => "SMAR",
                'countyName' => "SANTA MARIA",
                'regionCode' => "R5",
                'ineCountyCode' => '292',
                'queryMode' => '1',
                'coverageName' => "SANTA MARIA",
            ],
            [
                'countyCode' => "SDGO",
                'countyName' => "SANTO DOMINGO",
                'regionCode' => "R5",
                'ineCountyCode' => '325',
                'queryMode' => '1',
                'coverageName' => "SANTO DOMINGO",
            ],
            [
                'countyCode' => "VALP",
                'countyName' => "VALPARAISO",
                'regionCode' => "R5",
                'ineCountyCode' => '310',
                'queryMode' => '1',
                'coverageName' => "VALPARAISO",
            ],
            [
                'countyCode' => "VALE",
                'countyName' => "VILLA ALEMANA",
                'regionCode' => "R5",
                'ineCountyCode' => '315',
                'queryMode' => '1',
                'coverageName' => "VILLA ALEMANA",
            ],
            [
                'countyCode' => "VINA",
                'countyName' => "VINA DEL MAR",
                'regionCode' => "R5",
                'ineCountyCode' => '311',
                'queryMode' => '1',
                'coverageName' => "VINA DEL MAR",
            ],
            [
                'countyCode' => "CHEP",
                'countyName' => "CHEPICA",
                'regionCode' => "R6",
                'ineCountyCode' => '359',
                'queryMode' => '1',
                'coverageName' => "CHEPICA",
            ],
            [
                'countyCode' => "CHIM",
                'countyName' => "CHIMBARONGO",
                'regionCode' => "R6",
                'ineCountyCode' => '356',
                'queryMode' => '1',
                'coverageName' => "CHIMBARONGO",
            ],
            [
                'countyCode' => "CODE",
                'countyName' => "CODEGUA",
                'regionCode' => "R6",
                'ineCountyCode' => '338',
                'queryMode' => '1',
                'coverageName' => "CODEGUA",
            ],
            [
                'countyCode' => "COIN",
                'countyName' => "COINCO",
                'regionCode' => "R6",
                'ineCountyCode' => '349',
                'queryMode' => '1',
                'coverageName' => "COINCO",
            ],
            [
                'countyCode' => "COLT",
                'countyName' => "COLTAUCO",
                'regionCode' => "R6",
                'ineCountyCode' => '348',
                'queryMode' => '1',
                'coverageName' => "COLTAUCO",
            ],
            [
                'countyCode' => "DONI",
                'countyName' => "DONIHUE",
                'regionCode' => "R6",
                'ineCountyCode' => '350',
                'queryMode' => '1',
                'coverageName' => "DONIHUE",
            ],
            [
                'countyCode' => "GRAN",
                'countyName' => "GRANEROS",
                'regionCode' => "R6",
                'ineCountyCode' => '336',
                'queryMode' => '1',
                'coverageName' => "GRANEROS",
            ],
            [
                'countyCode' => "LCAB",
                'countyName' => "LAS CABRAS",
                'regionCode' => "R6",
                'ineCountyCode' => '351',
                'queryMode' => '1',
                'coverageName' => "LAS CABRAS",
            ],
            [
                'countyCode' => "LCHE",
                'countyName' => "LITUECHE",
                'regionCode' => "R6",
                'ineCountyCode' => '372',
                'queryMode' => '1',
                'coverageName' => "LITUECHE",
            ],
            [
                'countyCode' => "LOLO",
                'countyName' => "LOLOL",
                'regionCode' => "R6",
                'ineCountyCode' => '361',
                'queryMode' => '1',
                'coverageName' => "LOLOL",
            ],
            [
                'countyCode' => "MACH",
                'countyName' => "MACHALI",
                'regionCode' => "R6",
                'ineCountyCode' => '339',
                'queryMode' => '1',
                'coverageName' => "MACHALI",
            ],
            [
                'countyCode' => "MALO",
                'countyName' => "MALLOA",
                'regionCode' => "R6",
                'ineCountyCode' => '343',
                'queryMode' => '1',
                'coverageName' => "MALLOA",
            ],
            [
                'countyCode' => "MARC",
                'countyName' => "MARCHIHUE",
                'regionCode' => "R6",
                'ineCountyCode' => '374',
                'queryMode' => '1',
                'coverageName' => "MARCHIGUE",
            ],
            [
                'countyCode' => "NANC",
                'countyName' => "NANCAGUA",
                'regionCode' => "R6",
                'ineCountyCode' => '358',
                'queryMode' => '1',
                'coverageName' => "NANCAGUA",
            ],
            [
                'countyCode' => "OLIV",
                'countyName' => "OLIVAR",
                'regionCode' => "R6",
                'ineCountyCode' => '340',
                'queryMode' => '1',
                'coverageName' => "OLIVAR",
            ],
            [
                'countyCode' => "PALM",
                'countyName' => "PALMILLA",
                'regionCode' => "R6",
                'ineCountyCode' => '363',
                'queryMode' => '1',
                'coverageName' => "PALMILLA",
            ],
            [
                'countyCode' => "PERA",
                'countyName' => "PERALILLO",
                'regionCode' => "R6",
                'ineCountyCode' => '364',
                'queryMode' => '1',
                'coverageName' => "PERALILLO",
            ],
            [
                'countyCode' => "PEUM",
                'countyName' => "PEUMO",
                'regionCode' => "R6",
                'ineCountyCode' => '347',
                'queryMode' => '1',
                'coverageName' => "PEUMO",
            ],
            [
                'countyCode' => "PICD",
                'countyName' => "PICHIDEGUA",
                'regionCode' => "R6",
                'ineCountyCode' => '346',
                'queryMode' => '1',
                'coverageName' => "PICHIDEGUA",
            ],
            [
                'countyCode' => "PICH",
                'countyName' => "PICHILEMU",
                'regionCode' => "R6",
                'ineCountyCode' => '370',
                'queryMode' => '1',
                'coverageName' => "PICHILEMU",
            ],
            [
                'countyCode' => "QTIL",
                'countyName' => "QUINTA DE TILCOCO",
                'regionCode' => "R6",
                'ineCountyCode' => '344',
                'queryMode' => '1',
                'coverageName' => "QUINTA DE TILCOCO",
            ],
            [
                'countyCode' => "RANC",
                'countyName' => "RANCAGUA",
                'regionCode' => "R6",
                'ineCountyCode' => '335',
                'queryMode' => '1',
                'coverageName' => "RANCAGUA",
            ],
            [
                'countyCode' => "RENG",
                'countyName' => "RENGO",
                'regionCode' => "R6",
                'ineCountyCode' => '342',
                'queryMode' => '1',
                'coverageName' => "RENGO",
            ],
            [
                'countyCode' => "REQU",
                'countyName' => "REQUINOA",
                'regionCode' => "R6",
                'ineCountyCode' => '341',
                'queryMode' => '1',
                'coverageName' => "REQUINOA",
            ],
            [
                'countyCode' => "SFER",
                'countyName' => "SAN FERNANDO",
                'regionCode' => "R6",
                'ineCountyCode' => '355',
                'queryMode' => '1',
                'coverageName' => "SAN FERNANDO",
            ],
            [
                'countyCode' => "SFRA",
                'countyName' => "MOSTAZAL",
                'regionCode' => "R6",
                'ineCountyCode' => '337',
                'queryMode' => '1',
                'coverageName' => "SAN FRANCISCO DE MOSTAZAL",
            ],
            [
                'countyCode' => "SVIC",
                'countyName' => "SAN VICENTE",
                'regionCode' => "R6",
                'ineCountyCode' => '345',
                'queryMode' => '1',
                'coverageName' => "SAN VICENTE DE TAGUA TAGUA",
            ],
            [
                'countyCode' => "SCRU",
                'countyName' => "SANTA CRUZ",
                'regionCode' => "R6",
                'ineCountyCode' => '360',
                'queryMode' => '1',
                'coverageName' => "SANTA CRUZ",
            ],
            [
                'countyCode' => "CAUQ",
                'countyName' => "CAUQUENES",
                'regionCode' => "R7",
                'ineCountyCode' => '410',
                'queryMode' => '1',
                'coverageName' => "CAUQUENES",
            ],
            [
                'countyCode' => "COLB",
                'countyName' => "COLBUN",
                'regionCode' => "R7",
                'ineCountyCode' => '402',
                'queryMode' => '1',
                'coverageName' => "COLBUN",
            ],
            [
                'countyCode' => "CONS",
                'countyName' => "CONSTITUCION",
                'regionCode' => "R7",
                'ineCountyCode' => '397',
                'queryMode' => '1',
                'coverageName' => "CONSTITUCION",
            ],
            [
                'countyCode' => "CURI",
                'countyName' => "CURICO",
                'regionCode' => "R7",
                'ineCountyCode' => '380',
                'queryMode' => '1',
                'coverageName' => "CURICO",
            ],
            [
                'countyCode' => "HUAL",
                'countyName' => "HUALANE",
                'regionCode' => "R7",
                'ineCountyCode' => '385',
                'queryMode' => '1',
                'coverageName' => "HUALANE",
            ],
            [
                'countyCode' => "LINA",
                'countyName' => "LINARES",
                'regionCode' => "R7",
                'ineCountyCode' => '400',
                'queryMode' => '1',
                'coverageName' => "LINARES",
            ],
            [
                'countyCode' => "LONG",
                'countyName' => "LONGAVI",
                'regionCode' => "R7",
                'ineCountyCode' => '403',
                'queryMode' => '1',
                'coverageName' => "LONGAVI",
            ],
            [
                'countyCode' => "MOLI",
                'countyName' => "MOLINA",
                'regionCode' => "R7",
                'ineCountyCode' => '383',
                'queryMode' => '1',
                'coverageName' => "MOLINA",
            ],
            [
                'countyCode' => "PARR",
                'countyName' => "PARRAL",
                'regionCode' => "R7",
                'ineCountyCode' => '404',
                'queryMode' => '1',
                'coverageName' => "PARRAL",
            ],
            [
                'countyCode' => "ROME",
                'countyName' => "ROMERAL",
                'regionCode' => "R7",
                'ineCountyCode' => '382',
                'queryMode' => '1',
                'coverageName' => "ROMERAL",
            ],
            [
                'countyCode' => "SCLE",
                'countyName' => "SAN CLEMENTE",
                'regionCode' => "R7",
                'ineCountyCode' => '393',
                'queryMode' => '1',
                'coverageName' => "SAN CLEMENTE",
            ],
            [
                'countyCode' => "SJAV",
                'countyName' => "SAN JAVIER",
                'regionCode' => "R7",
                'ineCountyCode' => '407',
                'queryMode' => '1',
                'coverageName' => "SAN JAVIER",
            ],
            [
                'countyCode' => "TALC",
                'countyName' => "TALCA",
                'regionCode' => "R7",
                'ineCountyCode' => '390',
                'queryMode' => '1',
                'coverageName' => "TALCA",
            ],
            [
                'countyCode' => "TENO",
                'countyName' => "TENO",
                'regionCode' => "R7",
                'ineCountyCode' => '381',
                'queryMode' => '1',
                'coverageName' => "TENO",
            ],
            [
                'countyCode' => "VALG",
                'countyName' => "VILLA ALEGRE",
                'regionCode' => "R7",
                'ineCountyCode' => '406',
                'queryMode' => '1',
                'coverageName' => "VILLA ALEGRE",
            ],
            [
                'countyCode' => "ARAU",
                'countyName' => "ARAUCO",
                'regionCode' => "R8",
                'ineCountyCode' => '466',
                'queryMode' => '1',
                'coverageName' => "ARAUCO",
            ],
            [
                'countyCode' => "CABR",
                'countyName' => "CABRERO",
                'regionCode' => "R8",
                'ineCountyCode' => '441',
                'queryMode' => '1',
                'coverageName' => "CABRERO",
            ],
            [
                'countyCode' => "CANE",
                'countyName' => "CANETE",
                'regionCode' => "R8",
                'ineCountyCode' => '469',
                'queryMode' => '1',
                'coverageName' => "CANETE",
            ],
            [
                'countyCode' => "CHIG",
                'countyName' => "CHIGUAYANTE",
                'regionCode' => "R8",
                'ineCountyCode' => '474',
                'queryMode' => '1',
                'coverageName' => "CHIGUAYANTE",
            ],
            [
                'countyCode' => "CONC",
                'countyName' => "CONCEPCION",
                'regionCode' => "R8",
                'ineCountyCode' => '455',
                'queryMode' => '1',
                'coverageName' => "CONCEPCION",
            ],
            [
                'countyCode' => "CORO",
                'countyName' => "CORONEL",
                'regionCode' => "R8",
                'ineCountyCode' => '463',
                'queryMode' => '1',
                'coverageName' => "CORONEL",
            ],
            [
                'countyCode' => "CURA",
                'countyName' => "CURANILAHUE",
                'regionCode' => "R8",
                'ineCountyCode' => '467',
                'queryMode' => '1',
                'coverageName' => "CURANILAHUE",
            ],
            [
                'countyCode' => "HPEN",
                'countyName' => "HUALPEN",
                'regionCode' => "R8",
                'ineCountyCode' => '996',
                'queryMode' => '1',
                'coverageName' => "HUALPEN",
            ],
            [
                'countyCode' => "HAQI",
                'countyName' => "HUALQUI",
                'regionCode' => "R8",
                'ineCountyCode' => '460',
                'queryMode' => '1',
                'coverageName' => "HUALQUI",
            ],
            [
                'countyCode' => "LAJA",
                'countyName' => "LAJA",
                'regionCode' => "R8",
                'ineCountyCode' => '450',
                'queryMode' => '1',
                'coverageName' => "LAJA",
            ],
            [
                'countyCode' => "LEBU",
                'countyName' => "LEBU",
                'regionCode' => "R8",
                'ineCountyCode' => '465',
                'queryMode' => '1',
                'coverageName' => "LEBU",
            ],
            [
                'countyCode' => "ALAM",
                'countyName' => "LOS ALAMOS",
                'regionCode' => "R8",
                'ineCountyCode' => '468',
                'queryMode' => '1',
                'coverageName' => "LOS ALAMOS",
            ],
            [
                'countyCode' => "LANG",
                'countyName' => "LOS ANGELES",
                'regionCode' => "R8",
                'ineCountyCode' => '440',
                'queryMode' => '1',
                'coverageName' => "LOS ANGELES",
            ],
            [
                'countyCode' => "LOTA",
                'countyName' => "LOTA",
                'regionCode' => "R8",
                'ineCountyCode' => '462',
                'queryMode' => '1',
                'coverageName' => "LOTA",
            ],
            [
                'countyCode' => "MULC",
                'countyName' => "MULCHEN",
                'regionCode' => "R8",
                'ineCountyCode' => '447',
                'queryMode' => '1',
                'coverageName' => "MULCHEN",
            ],
            [
                'countyCode' => "NACI",
                'countyName' => "NACIMIENTO",
                'regionCode' => "R8",
                'ineCountyCode' => '449',
                'queryMode' => '1',
                'coverageName' => "NACIMIENTO",
            ],
            [
                'countyCode' => "NEGR",
                'countyName' => "NEGRETE",
                'regionCode' => "R8",
                'ineCountyCode' => '448',
                'queryMode' => '1',
                'coverageName' => "NEGRETE",
            ],
            [
                'countyCode' => "PENC",
                'countyName' => "PENCO",
                'regionCode' => "R8",
                'ineCountyCode' => '457',
                'queryMode' => '1',
                'coverageName' => "PENCO",
            ],
            [
                'countyCode' => "SPED",
                'countyName' => "SAN PEDRO DE LA PAZ",
                'regionCode' => "R8",
                'ineCountyCode' => '464',
                'queryMode' => '1',
                'coverageName' => "SAN PEDRO DE LA PAZ",
            ],
            [
                'countyCode' => "SANR",
                'countyName' => "SAN ROSENDO",
                'regionCode' => "R8",
                'ineCountyCode' => '451',
                'queryMode' => '1',
                'coverageName' => "SAN ROSENDO",
            ],
            [
                'countyCode' => "SBAR",
                'countyName' => "SANTA BARBARA",
                'regionCode' => "R8",
                'ineCountyCode' => '445',
                'queryMode' => '1',
                'coverageName' => "SANTA BARBARA",
            ],
            [
                'countyCode' => "THNO",
                'countyName' => "TALCAHUANO",
                'regionCode' => "R8",
                'ineCountyCode' => '456',
                'queryMode' => '1',
                'coverageName' => "TALCAHUANO",
            ],
            [
                'countyCode' => "TOME",
                'countyName' => "TOME",
                'regionCode' => "R8",
                'ineCountyCode' => '458',
                'queryMode' => '1',
                'coverageName' => "TOME",
            ],
            [
                'countyCode' => "TUCA",
                'countyName' => "TUCAPEL",
                'regionCode' => "R8",
                'ineCountyCode' => '442',
                'queryMode' => '1',
                'coverageName' => "TUCAPEL",
            ],
            [
                'countyCode' => "YUMB",
                'countyName' => "YUMBEL",
                'regionCode' => "R8",
                'ineCountyCode' => '452',
                'queryMode' => '1',
                'coverageName' => "YUMBEL",
            ],
            [
                'countyCode' => "ANGO",
                'countyName' => "ANGOL",
                'regionCode' => "R9",
                'ineCountyCode' => '475',
                'queryMode' => '1',
                'coverageName' => "ANGOL",
            ],
            [
                'countyCode' => "CARA",
                'countyName' => "CARAHUE",
                'regionCode' => "R9",
                'ineCountyCode' => '506',
                'queryMode' => '1',
                'coverageName' => "CARAHUE",
            ],
            [
                'countyCode' => "COLL",
                'countyName' => "COLLIPULLI",
                'regionCode' => "R9",
                'ineCountyCode' => '477',
                'queryMode' => '1',
                'coverageName' => "COLLIPULLI",
            ],
            [
                'countyCode' => "CURC",
                'countyName' => "CURACAUTIN",
                'regionCode' => "R9",
                'ineCountyCode' => '479',
                'queryMode' => '1',
                'coverageName' => "CURACAUTIN",
            ],
            [
                'countyCode' => "FRER",
                'countyName' => "FREIRE",
                'regionCode' => "R9",
                'ineCountyCode' => '499',
                'queryMode' => '1',
                'coverageName' => "FREIRE",
            ],
            [
                'countyCode' => "GORB",
                'countyName' => "GORBEA",
                'regionCode' => "R9",
                'ineCountyCode' => '501',
                'queryMode' => '1',
                'coverageName' => "GORBEA",
            ],
            [
                'countyCode' => "LAUT",
                'countyName' => "LAUTARO",
                'regionCode' => "R9",
                'ineCountyCode' => '491',
                'queryMode' => '1',
                'coverageName' => "LAUTARO",
            ],
            [
                'countyCode' => "LONC",
                'countyName' => "LONCOCHE",
                'regionCode' => "R9",
                'ineCountyCode' => '502',
                'queryMode' => '1',
                'coverageName' => "LONCOCHE",
            ],
            [
                'countyCode' => "NVAI",
                'countyName' => "NUEVA IMPERIAL",
                'regionCode' => "R9",
                'ineCountyCode' => '507',
                'queryMode' => '1',
                'coverageName' => "NUEVA IMPERIAL",
            ],
            [
                'countyCode' => "PLCA",
                'countyName' => "PADRE LAS CASAS",
                'regionCode' => "R9",
                'ineCountyCode' => '509',
                'queryMode' => '1',
                'coverageName' => "PADRE LAS CASAS",
            ],
            [
                'countyCode' => "PITR",
                'countyName' => "PITRUFQUEN",
                'regionCode' => "R9",
                'ineCountyCode' => '500',
                'queryMode' => '1',
                'coverageName' => "PITRUFQUEN",
            ],
            [
                'countyCode' => "PUCO",
                'countyName' => "PUCON",
                'regionCode' => "R9",
                'ineCountyCode' => '497',
                'queryMode' => '1',
                'coverageName' => "PUCON",
            ],
            [
                'countyCode' => "PURE",
                'countyName' => "PUREN",
                'regionCode' => "R9",
                'ineCountyCode' => '484',
                'queryMode' => '1',
                'coverageName' => "PUREN",
            ],
            [
                'countyCode' => "RNCO",
                'countyName' => "RENAICO",
                'regionCode' => "R9",
                'ineCountyCode' => '476',
                'queryMode' => '1',
                'coverageName' => "RENAICO",
            ],
            [
                'countyCode' => "TEMU",
                'countyName' => "TEMUCO",
                'regionCode' => "R9",
                'ineCountyCode' => '490',
                'queryMode' => '1',
                'coverageName' => "TEMUCO",
            ],
            [
                'countyCode' => "TRAI",
                'countyName' => "TRAIGUEN",
                'regionCode' => "R9",
                'ineCountyCode' => '482',
                'queryMode' => '1',
                'coverageName' => "TRAIGUEN",
            ],
            [
                'countyCode' => "VICT",
                'countyName' => "VICTORIA",
                'regionCode' => "R9",
                'ineCountyCode' => '481',
                'queryMode' => '1',
                'coverageName' => "VICTORIA",
            ],
            [
                'countyCode' => "VILL",
                'countyName' => "VILLARRICA",
                'regionCode' => "R9",
                'ineCountyCode' => '498',
                'queryMode' => '1',
                'coverageName' => "VILLARRICA",
            ],
            [
                'countyCode' => "BUIN",
                'countyName' => "BUIN",
                'regionCode' => "RM",
                'ineCountyCode' => '651',
                'queryMode' => '1',
                'coverageName' => "BUIN",
            ],
            [
                'countyCode' => "CTAN",
                'countyName' => "CALERA DE TANGO",
                'regionCode' => "RM",
                'ineCountyCode' => '653',
                'queryMode' => '1',
                'coverageName' => "CALERA DE TANGO",
            ],
            [
                'countyCode' => "LOSC",
                'countyName' => "CERRILLOS",
                'regionCode' => "RM",
                'ineCountyCode' => '629',
                'queryMode' => '1',
                'coverageName' => "CERRILLOS",
            ],
            [
                'countyCode' => "CNAV",
                'countyName' => "CERRO NAVIA",
                'regionCode' => "RM",
                'ineCountyCode' => '634',
                'queryMode' => '1',
                'coverageName' => "CERRO NAVIA",
            ],
            [
                'countyCode' => "COLI",
                'countyName' => "COLINA",
                'regionCode' => "RM",
                'ineCountyCode' => '640',
                'queryMode' => '1',
                'coverageName' => "COLINA",
            ],
            [
                'countyCode' => "CCHA",
                'countyName' => "CONCHALI",
                'regionCode' => "RM",
                'ineCountyCode' => '607',
                'queryMode' => '1',
                'coverageName' => "CONCHALI",
            ],
            [
                'countyCode' => "CRCV",
                'countyName' => "CURACAVI",
                'regionCode' => "RM",
                'ineCountyCode' => '662',
                'queryMode' => '1',
                'coverageName' => "CURACAVI",
            ],
            [
                'countyCode' => "ELBO",
                'countyName' => "EL BOSQUE",
                'regionCode' => "RM",
                'ineCountyCode' => '625',
                'queryMode' => '1',
                'coverageName' => "EL BOSQUE",
            ],
            [
                'countyCode' => "ELMO",
                'countyName' => "EL MONTE",
                'regionCode' => "RM",
                'ineCountyCode' => '673',
                'queryMode' => '1',
                'coverageName' => "EL MONTE",
            ],
            [
                'countyCode' => "ECEN",
                'countyName' => "ESTACION CENTRAL",
                'regionCode' => "RM",
                'ineCountyCode' => '628',
                'queryMode' => '1',
                'coverageName' => "ESTACION CENTRAL",
            ],
            [
                'countyCode' => "HUEC",
                'countyName' => "HUECHURABA",
                'regionCode' => "RM",
                'ineCountyCode' => '608',
                'queryMode' => '1',
                'coverageName' => "HUECHURABA",
            ],
            [
                'countyCode' => "INDE",
                'countyName' => "INDEPENDENCIA",
                'regionCode' => "RM",
                'ineCountyCode' => '606',
                'queryMode' => '1',
                'coverageName' => "INDEPENDENCIA",
            ],
            [
                'countyCode' => "IMAI",
                'countyName' => "ISLA DE MAIPO",
                'regionCode' => "RM",
                'ineCountyCode' => '672',
                'queryMode' => '1',
                'coverageName' => "ISLA DE MAIPO",
            ],
            [
                'countyCode' => "LACI",
                'countyName' => "LA CISTERNA",
                'regionCode' => "RM",
                'ineCountyCode' => '624',
                'queryMode' => '1',
                'coverageName' => "LA CISTERNA",
            ],
            [
                'countyCode' => "LAFL",
                'countyName' => "LA FLORIDA",
                'regionCode' => "RM",
                'ineCountyCode' => '618',
                'queryMode' => '1',
                'coverageName' => "LA FLORIDA",
            ],
            [
                'countyCode' => "LAGR",
                'countyName' => "LA GRANJA",
                'regionCode' => "RM",
                'ineCountyCode' => '620',
                'queryMode' => '1',
                'coverageName' => "LA GRANJA",
            ],
            [
                'countyCode' => "LAPI",
                'countyName' => "LA PINTANA",
                'regionCode' => "RM",
                'ineCountyCode' => '621',
                'queryMode' => '1',
                'coverageName' => "LA PINTANA",
            ],
            [
                'countyCode' => "LARE",
                'countyName' => "LA REINA",
                'regionCode' => "RM",
                'ineCountyCode' => '615',
                'queryMode' => '1',
                'coverageName' => "LA REINA",
            ],
            [
                'countyCode' => "LAMP",
                'countyName' => "LAMPA",
                'regionCode' => "RM",
                'ineCountyCode' => '641',
                'queryMode' => '1',
                'coverageName' => "LAMPA",
            ],
            [
                'countyCode' => "LCON",
                'countyName' => "LAS CONDES",
                'regionCode' => "RM",
                'ineCountyCode' => '613',
                'queryMode' => '1',
                'coverageName' => "LAS CONDES",
            ],
            [
                'countyCode' => "LOBA",
                'countyName' => "LO BARNECHEA",
                'regionCode' => "RM",
                'ineCountyCode' => '612',
                'queryMode' => '1',
                'coverageName' => "LO BARNECHEA",
            ],
            [
                'countyCode' => "LOES",
                'countyName' => "LO ESPEJO",
                'regionCode' => "RM",
                'ineCountyCode' => '627',
                'queryMode' => '1',
                'coverageName' => "LO ESPEJO",
            ],
            [
                'countyCode' => "LOPR",
                'countyName' => "LO PRADO",
                'regionCode' => "RM",
                'ineCountyCode' => '632',
                'queryMode' => '1',
                'coverageName' => "LO PRADO",
            ],
            [
                'countyCode' => "MACU",
                'countyName' => "MACUL",
                'regionCode' => "RM",
                'ineCountyCode' => '616',
                'queryMode' => '1',
                'coverageName' => "MACUL",
            ],
            [
                'countyCode' => "MIPU",
                'countyName' => "MAIPU",
                'regionCode' => "RM",
                'ineCountyCode' => '630',
                'queryMode' => '1',
                'coverageName' => "MAIPU",
            ],
            [
                'countyCode' => "MELI",
                'countyName' => "MELIPILLA",
                'regionCode' => "RM",
                'ineCountyCode' => '660',
                'queryMode' => '1',
                'coverageName' => "MELIPILLA",
            ],
            [
                'countyCode' => "NUNO",
                'countyName' => "NUNOA",
                'regionCode' => "RM",
                'ineCountyCode' => '614',
                'queryMode' => '1',
                'coverageName' => "NUNOA",
            ],
            [
                'countyCode' => "PHUR",
                'countyName' => "PADRE HURTADO",
                'regionCode' => "RM",
                'ineCountyCode' => '674',
                'queryMode' => '1',
                'coverageName' => "PADRE HURTADO",
            ],
            [
                'countyCode' => "PAIN",
                'countyName' => "PAINE",
                'regionCode' => "RM",
                'ineCountyCode' => '652',
                'queryMode' => '1',
                'coverageName' => "PAINE",
            ],
            [
                'countyCode' => "PEDR",
                'countyName' => "PEDRO AGUIRRE CERDA",
                'regionCode' => "RM",
                'ineCountyCode' => '626',
                'queryMode' => '1',
                'coverageName' => "PEDRO AGUIRRE CERDA",
            ],
            [
                'countyCode' => "PENA",
                'countyName' => "PENAFLOR",
                'regionCode' => "RM",
                'ineCountyCode' => '671',
                'queryMode' => '1',
                'coverageName' => "PENAFLOR",
            ],
            [
                'countyCode' => "PLOL",
                'countyName' => "PENALOLEN",
                'regionCode' => "RM",
                'ineCountyCode' => '617',
                'queryMode' => '1',
                'coverageName' => "PENALOLEN",
            ],
            [
                'countyCode' => "PIRQ",
                'countyName' => "PIRQUE",
                'regionCode' => "RM",
                'ineCountyCode' => '647',
                'queryMode' => '1',
                'coverageName' => "PIRQUE",
            ],
            [
                'countyCode' => "PROV",
                'countyName' => "PROVIDENCIA",
                'regionCode' => "RM",
                'ineCountyCode' => '610',
                'queryMode' => '1',
                'coverageName' => "PROVIDENCIA",
            ],
            [
                'countyCode' => "PUDA",
                'countyName' => "PUDAHUEL",
                'regionCode' => "RM",
                'ineCountyCode' => '633',
                'queryMode' => '1',
                'coverageName' => "PUDAHUEL",
            ],
            [
                'countyCode' => "PALT",
                'countyName' => "PUENTE ALTO",
                'regionCode' => "RM",
                'ineCountyCode' => '645',
                'queryMode' => '1',
                'coverageName' => "PUENTE ALTO",
            ],
            [
                'countyCode' => "QILI",
                'countyName' => "QUILICURA",
                'regionCode' => "RM",
                'ineCountyCode' => '636',
                'queryMode' => '1',
                'coverageName' => "QUILICURA",
            ],
            [
                'countyCode' => "QNOR",
                'countyName' => "QUINTA NORMAL",
                'regionCode' => "RM",
                'ineCountyCode' => '631',
                'queryMode' => '1',
                'coverageName' => "QUINTA NORMAL",
            ],
            [
                'countyCode' => "RECO",
                'countyName' => "RECOLETA",
                'regionCode' => "RM",
                'ineCountyCode' => '609',
                'queryMode' => '1',
                'coverageName' => "RECOLETA",
            ],
            [
                'countyCode' => "RENC",
                'countyName' => "RENCA",
                'regionCode' => "RM",
                'ineCountyCode' => '635',
                'queryMode' => '1',
                'coverageName' => "RENCA",
            ],
            [
                'countyCode' => "SBER",
                'countyName' => "SAN BERNARDO",
                'regionCode' => "RM",
                'ineCountyCode' => '650',
                'queryMode' => '1',
                'coverageName' => "SAN BERNARDO",
            ],
            [
                'countyCode' => "SJOA",
                'countyName' => "SAN JOAQUIN",
                'regionCode' => "RM",
                'ineCountyCode' => '619',
                'queryMode' => '1',
                'coverageName' => "SAN JOAQUIN",
            ],
            [
                'countyCode' => "SMIG",
                'countyName' => "SAN MIGUEL",
                'regionCode' => "RM",
                'ineCountyCode' => '623',
                'queryMode' => '1',
                'coverageName' => "SAN MIGUEL",
            ],
            [
                'countyCode' => "SRAM",
                'countyName' => "SAN RAMON",
                'regionCode' => "RM",
                'ineCountyCode' => '622',
                'queryMode' => '1',
                'coverageName' => "SAN RAMON",
            ],
            [
                'countyCode' => "STGO",
                'countyName' => "SANTIAGO CENTRO",
                'regionCode' => "RM",
                'ineCountyCode' => '605',
                'queryMode' => '1',
                'coverageName' => "SANTIAGO CENTRO",
            ],
            [
                'countyCode' => "SCOB",
                'countyName' => "SIN COBERTURA",
                'regionCode' => "RM",
                'ineCountyCode' => '0',
                'queryMode' => '1',
                'coverageName' => "SIN COBERTURA",
            ],
            [
                'countyCode' => "TALA",
                'countyName' => "TALAGANTE",
                'regionCode' => "RM",
                'ineCountyCode' => '670',
                'queryMode' => '1',
                'coverageName' => "TALAGANTE",
            ],
            [
                'countyCode' => "TILT",
                'countyName' => "TILTIL",
                'regionCode' => "RM",
                'ineCountyCode' => '642',
                'queryMode' => '1',
                'coverageName' => "TIL TIL",
            ],
            [
                'countyCode' => "VITA",
                'countyName' => "VITACURA",
                'regionCode' => "RM",
                'ineCountyCode' => '611',
                'queryMode' => '1',
                'coverageName' => "VITACURA",
            ],
            [
                'countyCode' => "ACHA",
                'countyName' => "QUINCHAO",
                'regionCode' => "R10",
                'ineCountyCode' => '550',
                'queryMode' => '1',
                'coverageName' => "ACHAO",
            ],
            [
                'countyCode' => "ANCU",
                'countyName' => "ANCUD",
                'regionCode' => "R10",
                'ineCountyCode' => '546',
                'queryMode' => '1',
                'coverageName' => "ANCUD",
            ],
            [
                'countyCode' => "CALB",
                'countyName' => "CALBUCO",
                'regionCode' => "R10",
                'ineCountyCode' => '538',
                'queryMode' => '1',
                'coverageName' => "CALBUCO",
            ],
            [
                'countyCode' => "CAST",
                'countyName' => "CASTRO",
                'regionCode' => "R10",
                'ineCountyCode' => '545',
                'queryMode' => '1',
                'coverageName' => "CASTRO",
            ],
            [
                'countyCode' => "CHAI",
                'countyName' => "CHAITEN",
                'regionCode' => "R10",
                'ineCountyCode' => '560',
                'queryMode' => '1',
                'coverageName' => "CHAITEN",
            ],
            [
                'countyCode' => "CHON",
                'countyName' => "CHONCHI",
                'regionCode' => "R10",
                'ineCountyCode' => '552',
                'queryMode' => '1',
                'coverageName' => "CHONCHI",
            ],
            [
                'countyCode' => "DALC",
                'countyName' => "DALCAHUE",
                'regionCode' => "R10",
                'ineCountyCode' => '548',
                'queryMode' => '1',
                'coverageName' => "DALCAHUE",
            ],
            [
                'countyCode' => "FRES",
                'countyName' => "FRESIA",
                'regionCode' => "R10",
                'ineCountyCode' => '541',
                'queryMode' => '1',
                'coverageName' => "FRESIA",
            ],
            [
                'countyCode' => "FRUT",
                'countyName' => "FRUTILLAR",
                'regionCode' => "R10",
                'ineCountyCode' => '543',
                'queryMode' => '1',
                'coverageName' => "FRUTILLAR",
            ],
            [
                'countyCode' => "HORP",
                'countyName' => "HUALAIHUE",
                'regionCode' => "R10",
                'ineCountyCode' => '561',
                'queryMode' => '1',
                'coverageName' => "HORNOPIREN",
            ],
            [
                'countyCode' => "LLAN",
                'countyName' => "LLANQUIHUE",
                'regionCode' => "R10",
                'ineCountyCode' => '542',
                'queryMode' => '1',
                'coverageName' => "LLANQUIHUE",
            ],
            [
                'countyCode' => "LMUE",
                'countyName' => "LOS MUERMOS",
                'regionCode' => "R10",
                'ineCountyCode' => '540',
                'queryMode' => '1',
                'coverageName' => "LOS MUERMOS",
            ],
            [
                'countyCode' => "MAUL",
                'countyName' => "MAULLIN",
                'regionCode' => "R10",
                'ineCountyCode' => '539',
                'queryMode' => '1',
                'coverageName' => "MAULLIN",
            ],
            [
                'countyCode' => "OSOR",
                'countyName' => "OSORNO",
                'regionCode' => "R10",
                'ineCountyCode' => '525',
                'queryMode' => '1',
                'coverageName' => "OSORNO",
            ],
            [
                'countyCode' => "PMON",
                'countyName' => "PUERTO MONTT",
                'regionCode' => "R10",
                'ineCountyCode' => '535',
                'queryMode' => '1',
                'coverageName' => "PUERTO MONTT",
            ],
            [
                'countyCode' => "POCT",
                'countyName' => "PUERTO OCTAY",
                'regionCode' => "R10",
                'ineCountyCode' => '528',
                'queryMode' => '1',
                'coverageName' => "PUERTO OCTAY",
            ],
            [
                'countyCode' => "PVAR",
                'countyName' => "PUERTO VARAS",
                'regionCode' => "R10",
                'ineCountyCode' => '536',
                'queryMode' => '1',
                'coverageName' => "PUERTO VARAS",
            ],
            [
                'countyCode' => "PURR",
                'countyName' => "PURRANQUE",
                'regionCode' => "R10",
                'ineCountyCode' => '529',
                'queryMode' => '1',
                'coverageName' => "PURRANQUE",
            ],
            [
                'countyCode' => "PUYG",
                'countyName' => "PUYEHUE",
                'regionCode' => "R10",
                'ineCountyCode' => '527',
                'queryMode' => '1',
                'coverageName' => "PUYEHUE",
            ],
            [
                'countyCode' => "QUEL",
                'countyName' => "QUELLON",
                'regionCode' => "R10",
                'ineCountyCode' => '554',
                'queryMode' => '1',
                'coverageName' => "QUELLON",
            ],
            [
                'countyCode' => "QUEM",
                'countyName' => "QUEMCHI",
                'regionCode' => "R10",
                'ineCountyCode' => '547',
                'queryMode' => '1',
                'coverageName' => "QUEMCHI",
            ],
            [
                'countyCode' => "RNEG",
                'countyName' => "RIO NEGRO",
                'regionCode' => "R10",
                'ineCountyCode' => '530',
                'queryMode' => '1',
                'coverageName' => "RIO NEGRO",
            ],
            [
                'countyCode' => "SPAB",
                'countyName' => "SAN PABLO",
                'regionCode' => "R10",
                'ineCountyCode' => '526',
                'queryMode' => '1',
                'coverageName' => "SAN PABLO",
            ],
            [
                'countyCode' => "CHCH",
                'countyName' => "CHILE CHICO",
                'regionCode' => "R11",
                'ineCountyCode' => '575',
                'queryMode' => '1',
                'coverageName' => "CHILE CHICO",
            ],
            [
                'countyCode' => "COCH",
                'countyName' => "COCHRANE",
                'regionCode' => "R11",
                'ineCountyCode' => '580',
                'queryMode' => '1',
                'coverageName' => "COCHRANE",
            ],
            [
                'countyCode' => "COYH",
                'countyName' => "COYHAIQUE",
                'regionCode' => "R11",
                'ineCountyCode' => '565',
                'queryMode' => '1',
                'coverageName' => "COYHAIQUE",
            ],
            [
                'countyCode' => "PAYS",
                'countyName' => "AISEN",
                'regionCode' => "R11",
                'ineCountyCode' => '570',
                'queryMode' => '1',
                'coverageName' => "PUERTO AYSEN",
            ],
            [
                'countyCode' => "PCIS",
                'countyName' => "CISNES",
                'regionCode' => "R11",
                'ineCountyCode' => '571',
                'queryMode' => '1',
                'coverageName' => "PUERTO CISNES",
            ],
            [
                'countyCode' => "PNAT",
                'countyName' => "NATALES",
                'regionCode' => "R12",
                'ineCountyCode' => '585',
                'queryMode' => '1',
                'coverageName' => "NATALES",
            ],
            [
                'countyCode' => "PORV",
                'countyName' => "PORVENIR",
                'regionCode' => "R12",
                'ineCountyCode' => '595',
                'queryMode' => '1',
                'coverageName' => "PORVENIR",
            ],
            [
                'countyCode' => "PUNT",
                'countyName' => "PUNTA ARENAS",
                'regionCode' => "R12",
                'ineCountyCode' => '590',
                'queryMode' => '1',
                'coverageName' => "PUNTA ARENAS",
            ],
            [
                'countyCode' => "FUTR",
                'countyName' => "FUTRONO",
                'regionCode' => "R14",
                'ineCountyCode' => '514',
                'queryMode' => '1',
                'coverageName' => "FUTRONO",
            ],
            [
                'countyCode' => "LAUN",
                'countyName' => "LA UNION",
                'regionCode' => "R14",
                'ineCountyCode' => '518',
                'queryMode' => '1',
                'coverageName' => "LA UNION",
            ],
            [
                'countyCode' => "LRAN",
                'countyName' => "LAGO RANCO",
                'regionCode' => "R14",
                'ineCountyCode' => '521',
                'queryMode' => '1',
                'coverageName' => "LAGO RANCO",
            ],
            [
                'countyCode' => "LANC",
                'countyName' => "LANCO",
                'regionCode' => "R14",
                'ineCountyCode' => '512',
                'queryMode' => '1',
                'coverageName' => "LANCO",
            ],
            [
                'countyCode' => "LLAG",
                'countyName' => "LOS LAGOS",
                'regionCode' => "R14",
                'ineCountyCode' => '513',
                'queryMode' => '1',
                'coverageName' => "LOS LAGOS",
            ],
            [
                'countyCode' => "MRQN",
                'countyName' => "MARIQUINA",
                'regionCode' => "R14",
                'ineCountyCode' => '511',
                'queryMode' => '1',
                'coverageName' => "MARIQUINA",
            ],
            [
                'countyCode' => "PAIL",
                'countyName' => "PAILLACO",
                'regionCode' => "R14",
                'ineCountyCode' => '519',
                'queryMode' => '1',
                'coverageName' => "PAILLACO",
            ],
            [
                'countyCode' => "PANG",
                'countyName' => "PANGUIPULLI",
                'regionCode' => "R14",
                'ineCountyCode' => '517',
                'queryMode' => '1',
                'coverageName' => "PANGUIPULLI",
            ],
            [
                'countyCode' => "RIOB",
                'countyName' => "RIO BUENO",
                'regionCode' => "R14",
                'ineCountyCode' => '520',
                'queryMode' => '1',
                'coverageName' => "RIO BUENO",
            ],
            [
                'countyCode' => "VALD",
                'countyName' => "VALDIVIA",
                'regionCode' => "R14",
                'ineCountyCode' => '510',
                'queryMode' => '1',
                'coverageName' => "VALDIVIA",
            ],
            [
                'countyCode' => "ARIC",
                'countyName' => "ARICA",
                'regionCode' => "R15",
                'ineCountyCode' => '201',
                'queryMode' => '1',
                'coverageName' => "ARICA",
            ],
            [
                'countyCode' => "BULN",
                'countyName' => "BULNES",
                'regionCode' => "R16",
                'ineCountyCode' => '425',
                'queryMode' => '1',
                'coverageName' => "BULNES",
            ],
            [
                'countyCode' => "CHIL",
                'countyName' => "CHILLAN",
                'regionCode' => "R16",
                'ineCountyCode' => '415',
                'queryMode' => '1',
                'coverageName' => "CHILLAN",
            ],
            [
                'countyCode' => "CHVJ",
                'countyName' => "CHILLAN VIEJO",
                'regionCode' => "R16",
                'ineCountyCode' => '435',
                'queryMode' => '1',
                'coverageName' => "CHILLAN VIEJO",
            ],
            [
                'countyCode' => "COEL",
                'countyName' => "COELEMU",
                'regionCode' => "R16",
                'ineCountyCode' => '429',
                'queryMode' => '1',
                'coverageName' => "COELEMU",
            ],
            [
                'countyCode' => "COIC",
                'countyName' => "COIHUECO",
                'regionCode' => "R16",
                'ineCountyCode' => '419',
                'queryMode' => '1',
                'coverageName' => "COIHUECO",
            ],
            [
                'countyCode' => "ECAR",
                'countyName' => "EL CARMEN",
                'regionCode' => "R16",
                'ineCountyCode' => '422',
                'queryMode' => '1',
                'coverageName' => "EL CARMEN",
            ],
            [
                'countyCode' => "PEMU",
                'countyName' => "PEMUCO",
                'regionCode' => "R16",
                'ineCountyCode' => '424',
                'queryMode' => '1',
                'coverageName' => "PEMUCO",
            ],
            [
                'countyCode' => "PINT",
                'countyName' => "PINTO",
                'regionCode' => "R16",
                'ineCountyCode' => '420',
                'queryMode' => '1',
                'coverageName' => "PINTO",
            ],
            [
                'countyCode' => "QULL",
                'countyName' => "QUILLON",
                'regionCode' => "R16",
                'ineCountyCode' => '426',
                'queryMode' => '1',
                'coverageName' => "QUILLON",
            ],
            [
                'countyCode' => "QUIR",
                'countyName' => "QUIRIHUE",
                'regionCode' => "R16",
                'ineCountyCode' => '432',
                'queryMode' => '1',
                'coverageName' => "QUIRIHUE",
            ],
            [
                'countyCode' => "SCAR",
                'countyName' => "SAN CARLOS",
                'regionCode' => "R16",
                'ineCountyCode' => '416',
                'queryMode' => '1',
                'coverageName' => "SAN CARLOS",
            ],
            [
                'countyCode' => "SIGN",
                'countyName' => "SAN IGNACIO",
                'regionCode' => "R16",
                'ineCountyCode' => '421',
                'queryMode' => '1',
                'coverageName' => "SAN IGNACIO",
            ],
            [
                'countyCode' => "YUNG",
                'countyName' => "YUNGAY",
                'regionCode' => "R16",
                'ineCountyCode' => '423',
                'queryMode' => '1',
                'coverageName' => "YUNGAY",
            ],
        ])->each(function ($county) {
           SystemCounty::updateOrCreate(['countyCode' => $county['countyCode']], $county);
        });
    }
}
